import sys
from enum import Enum, IntEnum

EARTH_EQUATORIAL_CIRCUMFERENCE_M = 40075000  # meters
EARTH_POLAR_CIRCUMFERENCE_M = 40007000  # meters


class BeaconType(IntEnum):
    CIVILIAN_AIRPORT = 0xF5
    CIVILIAN_HELIPORT = 0xF6
    CIVILIAN_SEABASE = 0xF7
    MILITARY_AIRPORT = 0xF8
    MILITARY_HELIPORT = 0xF9  # invalid: military beacons are supported only for airfields
    MILITARY_SEA_BASE = 0xFA  # invalid: military beacons are supported only for airfields


class ImageComplexity(IntEnum):
    VERY_SPARSE = 0x00
    SPARSE = 0x01
    NORMAL = 0x02
    DENSE = 0x03
    VERY_DENSE = 0x04
    EXTREMELY_DENSE = 0x05


class TaxiwaySignJustification(IntEnum):
    RIGHT = 0x01
    LEFT = 0x02


class BGLSectionType(IntEnum):
    NONE = 0x0
    COPYRIGHT = 0x1
    GUID = 0x2
    AIRPORT = 0x3
    ILS_VOR = 0x13
    NDB = 0x17
    MARKER = 0x18
    BOUNDARY = 0x20
    WAYPOINT = 0x22
    GEOPOL = 0x23
    SCENERYOBJECT = 0x25
    NAMELIST = 0x27
    VORILSICAOINDEX = 0x28
    NDBICAOINDEX = 0x29
    WAYPOINTICAOINDEX = 0x2A
    MODELDATA = 0x2B
    AIRPORTSUMMARY = 0x2C
    EXCLUSION = 0x2E
    TIMEZONE = 0x2F
    TERRAINVECTORDB = 0x65
    TERRAINELEVATION = 0x67
    TERRAINLANDCLASS = 0x68
    TERRAINWATERCLASS = 0x69
    TERRAINREGION = 0x6A
    POPULATIONDENSITY = 0x6C
    AUTOGENANNOTATION = 0x6D
    TERRAININDEX = 0x6E
    TERRAINTEXTURELOOKUP = 0x6F
    TERRAINSEASONJAN = 0x78
    TERRAINSEASONFEB = 0x79
    TERRAINSEASONMAR = 0x7A
    TERRAINSEASONAPR = 0x7B
    TERRAINSEASONMAY = 0x7C
    TERRAINSEASONJUN = 0x7D
    TERRAINSEASONJUL = 0x7E
    TERRAINSEASONAUG = 0x7F
    TERRAINSEASONSEP = 0x80
    TERRAINSEASONOCT = 0x81
    TERRAINSEASONNOV = 0x82
    TERRAINSEASONDEC = 0x83
    TERRAINPHOTOJAN = 0x8C
    TERRAINPHOTOFEB = 0x8D
    TERRAINPHOTOMAR = 0x8E
    TERRAINPHOTOAPR = 0x8F
    TERRAINPHOTOMAY = 0x90
    TERRAINPHOTOJUN = 0x91
    TERRAINPHOTOJUL = 0x92
    TERRAINPHOTOAUG = 0x93
    TERRAINPHOTOSEP = 0x94
    TERRAINPHOTOOCT = 0x95
    TERRAINPHOTONOV = 0x96
    TERRAINPHOTODEC = 0x97
    TERRAINPHOTONIGHT = 0x98
    TACAN = 0xA0
    TACANINDEX = 0xA1
    FAKETYPES = 0x2710
    ICAORUNWAY = 0x2711


# StrEnum is available only for python >= 3.11
if sys.version_info < (3, 11):
    class StrEnum(str, Enum):
        pass
else:
    from enum import StrEnum


class FSVersion(StrEnum):
    FS9 = "FS2004"
    FSX = "FSX"
    MSFS = "MSFS"


BIGGER_SECTION_TYPES = [

    BGLSectionType.TERRAINELEVATION,
    BGLSectionType.TERRAINLANDCLASS,
    BGLSectionType.TERRAINWATERCLASS,
    BGLSectionType.TERRAINREGION,
    BGLSectionType.POPULATIONDENSITY,
    BGLSectionType.TERRAININDEX,
    BGLSectionType.TERRAINSEASONJAN,
    BGLSectionType.TERRAINSEASONFEB,
    BGLSectionType.TERRAINSEASONMAR,
    BGLSectionType.TERRAINSEASONAPR,
    BGLSectionType.TERRAINSEASONMAY,
    BGLSectionType.TERRAINSEASONJUN,
    BGLSectionType.TERRAINSEASONJUL,
    BGLSectionType.TERRAINSEASONAUG,
    BGLSectionType.TERRAINSEASONSEP,
    BGLSectionType.TERRAINSEASONOCT,
    BGLSectionType.TERRAINSEASONNOV,
    BGLSectionType.TERRAINSEASONDEC,
    BGLSectionType.TERRAINPHOTOJAN,
    BGLSectionType.TERRAINPHOTOFEB,
    BGLSectionType.TERRAINPHOTOMAR,
    BGLSectionType.TERRAINPHOTOAPR,
    BGLSectionType.TERRAINPHOTOMAY,
    BGLSectionType.TERRAINPHOTOJUN,
    BGLSectionType.TERRAINPHOTOJUL,
    BGLSectionType.TERRAINPHOTOAUG,
    BGLSectionType.TERRAINPHOTOSEP,
    BGLSectionType.TERRAINPHOTOOCT,
    BGLSectionType.TERRAINPHOTONOV,
    BGLSectionType.TERRAINPHOTODEC,
    BGLSectionType.TERRAINPHOTONIGHT,
]
